-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 11:55:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdsae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdsae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsae` DEFAULT CHARACTER SET utf8 ;
USE `bdsae` ;

-- -----------------------------------------------------
-- Table `bdsae`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(120) NOT NULL,
  `telephone` VARCHAR(12) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `mdp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Adherent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Adherent` (
  `derniereVisite` DATE NULL,
  `derniereInscription` DATE NULL,
  `niveauPratique` VARCHAR(45) NULL,
  `photo` BLOB NULL,
  `Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`),
  INDEX `fk_Adherent_Personne1_idx` (`Personne_idPersonne` ASC),
  CONSTRAINT `fk_Adherent_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `bdsae`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Circuit` (
  `idCircuit` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(120) NOT NULL,
  `nbrMaxPlace` INT NOT NULL,
  `disponible` TINYINT NOT NULL,
  PRIMARY KEY (`idCircuit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Admin` (
  `Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`),
  INDEX `fk_Admin_Personne1_idx` (`Personne_idPersonne` ASC),
  CONSTRAINT `fk_Admin_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `bdsae`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Reservation` (
  `idRéservation` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `heureDebut` TIME NOT NULL,
  `heureFin` TIME NOT NULL,
  `nombreParticipant` INT NOT NULL,
  `Circuit_idCircuit` INT NOT NULL,
  `Adherent_Personne_idPersonne` INT NOT NULL,
  `Admin_Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idRéservation`),
  INDEX `fk_Reservation_Circuit1_idx` (`Circuit_idCircuit` ASC),
  INDEX `fk_Reservation_Adherent1_idx` (`Adherent_Personne_idPersonne` ASC),
  INDEX `fk_Reservation_Admin1_idx` (`Admin_Personne_idPersonne` ASC),
  CONSTRAINT `fk_Reservation_Circuit1`
    FOREIGN KEY (`Circuit_idCircuit`)
    REFERENCES `bdsae`.`Circuit` (`idCircuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Adherent1`
    FOREIGN KEY (`Adherent_Personne_idPersonne`)
    REFERENCES `bdsae`.`Adherent` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Admin1`
    FOREIGN KEY (`Admin_Personne_idPersonne`)
    REFERENCES `bdsae`.`Admin` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Match` (
  `idMatch` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `heureDebut` TIME NOT NULL,
  `heureFin` TIME NOT NULL,
  `nbrPartNecessaire` INT NOT NULL,
  `Gagnant` INT NULL,
  `resultatFinal` VARCHAR(45) NULL,
  `Circuit_idCircuit` INT NOT NULL,
  `Admin_Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idMatch`),
  INDEX `fk_Match_Circuit1_idx` (`Circuit_idCircuit` ASC),
  INDEX `fk_Match_Admin1_idx` (`Admin_Personne_idPersonne` ASC),
  INDEX `fk_Match_Adherent2_idx` (`Gagnant` ASC),
  CONSTRAINT `fk_Match_Circuit1`
    FOREIGN KEY (`Circuit_idCircuit`)
    REFERENCES `bdsae`.`Circuit` (`idCircuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Admin1`
    FOREIGN KEY (`Admin_Personne_idPersonne`)
    REFERENCES `bdsae`.`Admin` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_Adherent2`
    FOREIGN KEY (`Gagnant`)
    REFERENCES `bdsae`.`Adherent` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `contenu` LONGTEXT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `dateMAJ` DATE NOT NULL,
  `Admin_Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_Article_Admin1_idx` (`Admin_Personne_idPersonne` ASC),
  CONSTRAINT `fk_Article_Admin1`
    FOREIGN KEY (`Admin_Personne_idPersonne`)
    REFERENCES `bdsae`.`Admin` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsae`.`Match_has_Adherent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsae`.`Match_has_Adherent` (
  `Match_idMatch` INT NOT NULL,
  `Adherent_Personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`Match_idMatch`, `Adherent_Personne_idPersonne`),
  INDEX `fk_Match_has_Adherent_Adherent1_idx` (`Adherent_Personne_idPersonne` ASC),
  INDEX `fk_Match_has_Adherent_Match1_idx` (`Match_idMatch` ASC),
  CONSTRAINT `fk_Match_has_Adherent_Match1`
    FOREIGN KEY (`Match_idMatch`)
    REFERENCES `bdsae`.`Match` (`idMatch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Adherent_Adherent1`
    FOREIGN KEY (`Adherent_Personne_idPersonne`)
    REFERENCES `bdsae`.`Adherent` (`Personne_idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
